"""Installer-facing config flow for Homapel Conversation.

Per ARCHITECTURE.md §4 and §7.7.3, the `api_key` is generated by the cloud
during `POST /v1/units/register` (called by the installer tool with a
separate installer JWT). The installer then seeds it into HA either by
calling HA's REST API directly, or — as a manual fallback — by opening
this config flow and pasting the value.

This flow validates the provided key by calling §7.3.3 `GET /v1/units/status`
and uses the returned `unit_id` as the config entry's unique_id.
"""
from __future__ import annotations

import logging
from typing import Any

import voluptuous as vol
from homeassistant.config_entries import ConfigFlow, ConfigFlowResult
from homeassistant.helpers.aiohttp_client import async_get_clientsession

from .api import (
    HomapelAuthError,
    HomapelCloudClient,
    HomapelForbiddenError,
    HomapelNetworkError,
    HomapelTimeoutError,
)
from .const import (
    CONF_API_BASE,
    CONF_API_KEY,
    CONF_DEFAULT_LANGUAGE,
    CONF_UNIT_ID,
    DEFAULT_API_BASE,
    DEFAULT_LANGUAGE,
    DOMAIN,
    SUPPORTED_LANGUAGES,
)

_LOGGER = logging.getLogger(__name__)


class HomapelConfigFlow(ConfigFlow, domain=DOMAIN):
    """Handle a config flow for Homapel Conversation."""

    VERSION = 1

    async def async_step_user(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        errors: dict[str, str] = {}

        if user_input is not None:
            api_key = user_input[CONF_API_KEY].strip()
            api_base = user_input.get(CONF_API_BASE, DEFAULT_API_BASE).rstrip("/")
            default_language = user_input.get(CONF_DEFAULT_LANGUAGE, DEFAULT_LANGUAGE)

            session = async_get_clientsession(self.hass)
            client = HomapelCloudClient(session, api_base)

            try:
                status = await client.get_status(api_key)
            except HomapelAuthError:
                errors["base"] = "invalid_auth"
            except HomapelForbiddenError:
                errors["base"] = "forbidden"
            except HomapelTimeoutError:
                errors["base"] = "timeout"
            except HomapelNetworkError:
                errors["base"] = "cannot_connect"
            except Exception:  # noqa: BLE001
                _LOGGER.exception("Unexpected error validating api_key")
                errors["base"] = "unknown"
            else:
                await self.async_set_unique_id(status.unit_id)
                self._abort_if_unique_id_configured()
                return self.async_create_entry(
                    title=f"Homapel ({status.unit_id})",
                    data={
                        CONF_API_BASE: api_base,
                        CONF_API_KEY: api_key,
                        CONF_UNIT_ID: status.unit_id,
                        CONF_DEFAULT_LANGUAGE: default_language,
                    },
                )

        schema = vol.Schema(
            {
                vol.Required(CONF_API_KEY): str,
                vol.Optional(CONF_API_BASE, default=DEFAULT_API_BASE): str,
                vol.Optional(CONF_DEFAULT_LANGUAGE, default=DEFAULT_LANGUAGE): vol.In(
                    SUPPORTED_LANGUAGES
                ),
            }
        )
        return self.async_show_form(step_id="user", data_schema=schema, errors=errors)
